# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            garrett honke 
tagline:          'computational neuroscientist'
description:      'computational neuroscientist'
url:              ghonk.github.io
baseurl:          /

author:
  name:           'garrett honke'
  url:            https://twitter.com/garretthonke

# plugins
plugins:
  - redcarpet
  - jekyll-gist
  - pygments.rb
